version: '3'
services:
  django_service: 
    container_name: django_container
    image: django_image
    ports:
      - "8000:8000"
    command: tail -f /dev/null
    volumes: 
      - "./django_shared:/app"
    networks:
      - net
    build:
      context: django_folder
    
  remote_host_service:
    container_name: remote-host_container
    image: remote-host_image
    volumes: 
      - "./ubuntu_shared:/usr/src"
    command: /usr/sbin/sshd -D
    build:
      context: ubuntu_folder
    networks:
      - net
      
  mysql_host_service:
    container_name: mysql_host_container
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes: 
      - "./mysql_shared:/var/lib/mysql"
    networks:
      - net
      
networks: 
  net:
